### PR TITLE
fix: Change display of uses/used by, cleanup repocard usage

### LINKED ISSUE #124: ZUI: minor changes for uses/used by tabs
- change the computer screen to N/A if no items are found
- remove "Depends On" and "Is Dependent On" text

### LINKED ISSUE #129: ZUI: use tiles to view results in the uses / used by tabs

### PR DESCRIPTION
**Pull request by raulkele**
Signed-off-by: Raul Kele <raulkeleblk@gmail.com>

**What type of PR is this?**
cleanup

**Which issue does this PR fix**:
Closes #124 
Closes #129 

**What does this PR do / Why do we need it**:
Updated used by/uses tabs to use cards and removed unnecessary parts of ui

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note
- Removed unnecessary text in uses and used by tabs on image page
- Changed display of used used by images to cards instead of text
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/components/HistoryLayers.jsx [hunk 1]
```diff
@@ -210,7 +210,6 @@ function HistoryLayers(props) {
         </Card>
       ) : (
         <div>
-          <img src={Monitor} alt="Monitor" className={classes.monitor}></img>
```
Comment (ameliamariabreda) [inline src/components/HistoryLayers.jsx:213]: import of the source image should be also erased

**Review by ameliamariabreda — APPROVED** [review]
lgtm
